const SANITY_ENDPOINT='https://tnmhhac3.api.sanity.io/v2024-09-30/data/query/production';
const FALLBACK_IMAGE='images/conference-hero.webp';
const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const money=c=>c===0?'Free':`$${(c/100).toLocaleString('en-US',{minimumFractionDigits:c%100?2:0})}`;
const date=v=>v?new Date(v).toLocaleDateString('en-US',{weekday:'short',month:'long',day:'numeric',year:'numeric'}):'Date announced soon';
const time=v=>v?new Date(v).toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'}):'';
async function querySanity(query,params={}){const u=new URL(SANITY_ENDPOINT);u.searchParams.set('query',query);Object.entries(params).forEach(([k,v])=>u.searchParams.set(`$${k}`,JSON.stringify(v)));const r=await fetch(u);if(!r.ok)throw new Error('Events could not be loaded');return(await r.json()).result}
const listQuery=`*[_type=="event"&&site=="sabwb"]|order(featured desc,startDate asc){_id,title,"slug":slug.current,kind,tagline,featured,startDate,endDate,location,"heroImageUrl":heroImage.asset->url,priceTiers[]{label,priceCents,description,soldOut}}`;
const detailQuery=`*[_type=="event"&&site=="sabwb"&&slug.current==$slug][0]{_id,title,"slug":slug.current,kind,tagline,startDate,endDate,timezone,location,"heroImageUrl":heroImage.asset->url,"experienceImageUrl":experienceImage.asset->url,"experienceVideoUrl":experienceVideo.asset->url,about,agenda[]{time,title,detail},"speakers":speakers[]->{name,role,bio,"imageUrl":headshot.asset->url},priceTiers[]{label,priceCents,description,soldOut},faq[]{q,a}}`;
function card(e){const first=(e.priceTiers||[]).find(t=>!t.soldOut);return `<a class="event-card" href="event.html?slug=${encodeURIComponent(e.slug)}"><img src="${esc(e.heroImageUrl||FALLBACK_IMAGE)}" alt="${esc(e.title)}"><div class="event-card-body"><div class="event-tag">${esc(e.kind||'Event')}</div><h3>${esc(e.title)}</h3><div class="event-meta">${esc(date(e.startDate))}<br>${esc(e.location?.name||e.location?.city||'Location announced soon')}</div><div class="event-price">${first?`From ${money(first.priceCents)}`:'Registration details coming soon'} →</div></div></a>`}
async function renderList(){const grid=document.getElementById('event-grid');try{const events=await querySanity(listQuery);grid.innerHTML=events.length?events.map(card).join(''):'<div class="empty">New SABWB events will appear here as soon as they are published in Sanity.</div>'}catch(e){grid.innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
function tierMarkup(t,i){return `<button class="tier${i===0?' active':''}" data-tier="${esc(t.label)}" ${t.soldOut?'disabled':''}><span class="tier-price">${money(t.priceCents)}</span><strong>${esc(t.label)}</strong><span>${esc(t.soldOut?'Sold out':t.description||'Admission')}</span></button>`}
async function renderDetail(){const slug=new URLSearchParams(location.search).get('slug');if(!slug){location.replace('events.html');return}const root=document.getElementById('event-page');try{const e=await querySanity(detailQuery,{slug});if(!e)throw new Error('This event was not found.');document.title=`${e.title} — SABWB`;root.innerHTML=`<section class="detail-hero"><img src="${esc(e.heroImageUrl||FALLBACK_IMAGE)}" alt="${esc(e.title)}"><div class="detail-copy"><div class="eyebrow">${esc(e.kind||'SABWB Event')}</div><h1>${esc(e.title)}</h1><div class="detail-meta"><span>${esc(date(e.startDate))}${e.endDate?` – ${esc(date(e.endDate))}`:''}</span><span>${esc(e.location?.name||'Location announced soon')}</span></div></div></section><div class="event-layout"><article class="event-content">${e.experienceVideoUrl?`<video class="experience" controls src="${esc(e.experienceVideoUrl)}"${e.experienceImageUrl?` poster="${esc(e.experienceImageUrl)}"`:''}></video>`:e.experienceImageUrl?`<img class="experience" src="${esc(e.experienceImageUrl)}" alt="${esc(e.title)} experience">`:''}<h2>About this event</h2>${(e.about||[]).map(p=>`<p>${esc(p)}</p>`).join('')||`<p>${esc(e.tagline||'Full event information is coming soon.')}</p>`}${e.agenda?.length?`<h2>Schedule</h2><div class="agenda">${e.agenda.map(a=>`<div class="agenda-row"><strong>${esc(a.time)}</strong><div><b>${esc(a.title)}</b>${a.detail?`<p>${esc(a.detail)}</p>`:''}</div></div>`).join('')}</div>`:''}${e.speakers?.length?`<h2>Speakers</h2><div class="speakers">${e.speakers.map(s=>`<div class="speaker">${s.imageUrl?`<img src="${esc(s.imageUrl)}" alt="${esc(s.name)}">`:''}<div><h3>${esc(s.name)}</h3><p>${esc(s.role||'Speaker')}</p></div></div>`).join('')}</div>`:''}${e.faq?.length?`<h2>Frequently asked questions</h2><div class="faq">${e.faq.map(f=>`<details><summary>${esc(f.q)}</summary><p>${esc(f.a)}</p></details>`).join('')}</div>`:''}</article><aside class="checkout-card"><h2>Tickets</h2><p>${esc(date(e.startDate))} · ${esc(time(e.startDate))}</p><div class="tiers">${(e.priceTiers||[]).map(tierMarkup).join('')||'<div class="free-message">Registration details coming soon.</div>'}</div><label for="ticket-quantity">Quantity</label><select class="quantity" id="ticket-quantity"><option>1</option><option>2</option><option>3</option><option>4</option><option>5</option></select><p id="checkout-error" class="error"></p><div id="event-checkout" class="checkout-mount"></div></aside></div>`;wireCheckout(e)}catch(err){root.innerHTML=`<main><div class="empty">${esc(err.message)} <a href="events.html">Back to events</a></div></main>`}}
function wireCheckout(e){const tiers=[...document.querySelectorAll('.tier:not([disabled])')];let selected=tiers[0]||null;let embedded=null;tiers.forEach(b=>b.onclick=()=>{tiers.forEach(x=>x.classList.remove('active'));b.classList.add('active');selected=b;start()});async function start(){if(!selected)return;const tier=(e.priceTiers||[]).find(t=>t.label===selected.dataset.tier);const mount=document.getElementById('event-checkout');if(!tier||tier.priceCents===0){if(embedded){embedded.destroy();embedded=null}mount.innerHTML='<div class="free-message">Loading free registration…</div>';try{const links=await fetch('/api/event-links').then(r=>r.json());const href=e.slug==='time-to-rise-conference'?links.conference:links.allEvents;mount.innerHTML=href?`<div class="free-message"><b>Free admission</b><br><br><a class="nav-links cta" href="${esc(href)}">Reserve your seat →</a></div>`:'<div class="free-message">This ticket is free. Registration details will be posted here.</div>'}catch(_){mount.innerHTML='<div class="free-message">This ticket is free. Registration details will be posted here.</div>'}return}document.getElementById('checkout-error').textContent='';try{if(embedded)embedded.destroy();const r=await fetch('/api/create-event-session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({eventSlug:e.slug,tierLabel:tier.label,quantity:Number(document.getElementById('ticket-quantity').value)})});const data=await r.json();if(!r.ok)throw new Error(data.error||'Checkout could not be started');embedded=await Stripe(data.publishableKey).initEmbeddedCheckout({clientSecret:data.clientSecret});mount.innerHTML='';embedded.mount('#event-checkout')}catch(err){document.getElementById('checkout-error').textContent=err.message}}document.getElementById('ticket-quantity').onchange=start;start()}
document.body.dataset.page==='events-list'?renderList():renderDetail();
